image: ubuntu/cosmic
packages:
  - autotools-dev
  - autoconf
  - automake
  - pkg-config
  - libtool
  - guile-2.2
  - guile-2.2-dev
sources:
  - https://git.sr.ht/~amz3/guile-arew
tasks:
#  - bootstrap: cd guile-arew && ./bootstrap
#  - configure: cd guile-arew && ./configure
#  - make: cd guile-arew && make
  - check: cd guile-arew && guile -L . check.scm
